---
description: "SDD output directory configuration — all spec artifacts must be written to the structured specs/ folder"
alwaysApply: true
---

# SDD Output Directory Configuration (Mandatory)

All SDD artifacts generated by the agent MUST be written to the structured `specs/` directory **within the current workspace root**. Never write artifacts to locations outside the workspace root.

## Output Structure

```
specs/
└── {slug}/
    ├── {slug}.spec.md       ← Step 1 (speckit.specify)
    ├── {slug}.backlog.md    ← Step 3 (speckit.backlog)
    ├── {slug}.plan.md       ← Step 4 (speckit.plan)
    └── {slug}.tasks.md      ← Step 4 (speckit.tasks)
```

## Rules

1. **Workspace-relative output.** The `specs/` directory lives at the **workspace root**. All spec and backlog artifacts go under `specs/`.

2. **Slug derivation.** Use the feature name converted to `kebab-case` as the slug. Examples:
   - "Saved Views for Reports" → `specs/saved-views-for-reports/`
   - "Document Upload" → `specs/document-upload/`

3. **Never write outside the workspace.** If the workspace contains multiple repos (multi-root), write to `specs/` under the **workspace root** being worked on.

4. **Announce the output path.** When creating the first file for a feature, tell the user:
   > "Writing artifacts to `specs/{slug}/`. All subsequent step outputs will go to this directory."

5. **Existing output.** If `specs/{slug}/` already has files from a previous run, do NOT overwrite without asking. Inform the user and ask whether to overwrite or create a versioned file.

## User Override

If the user specifies a custom output path, honor that path instead. The custom path still must be within the workspace root.
